import fandango

# regex: (?:x(?:...|(...))\1x)+

# Grammar:

# Generated EBNF Grammar for Fandango Fuzzer

<start> ::= (<r0>)+

<r1> ::= <byte> <byte> <byte>
<r3> ::= <byte> <byte> <byte>
<r2> ::= <r3>
<r4> ::= <byte> <byte> <byte>
<r0> ::= "x" (<r1> | <r2>) <r4> "x"

# Constraints:

# No lookaround constraints


# Capture group reference constraints

where assert_group_equality_r3_r4(<r0>)

# Generators:

# Helper function to find the substring generated by a particular nonterminal in the derivation tree, used for capture group reference constraints
def find_sub_nt(tree, target_nt):
    if str(tree.symbol) == target_nt:
        return tree
    for child in tree.children:
        result = find_sub_nt(child, target_nt)
        if result is not None:
            return result
    return None


# Capture group reference constraint definitions

def assert_group_equality_r3_r4(p):
    """Constraint to enforce equality of group reference <r4> to its referenced rule <r3> under ancestor rule <r0>"""
    return str(find_sub_nt(p, "<r3>")) == str(find_sub_nt(p, "<r4>"))